/// A simple data structure representing an item in a button group menu.
///
/// Used by [SplitButton] and the overflow menu generated by
/// [ButtonGroup] when collapsing trailing actions into a “More” menu.
class MenuEntry {
  /// Creates a menu entry.
  const MenuEntry(this.label, {this.icon, this.onSelected});

  /// The human readable label for this menu entry.
  final String label;

  /// An optional icon to display next to the label.
  final dynamic icon;

  /// Callback invoked when this menu entry is selected.
  final void Function()? onSelected;
}