name: button_group_example
description: Example application for the button_group package.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  button_group:
    path: ../

flutter:
  uses-material-design: true