name: button_group
description: A Material 3 Expressive inspired button group widget for Flutter that lays out action buttons in either a standard or connected style. The group supports multiple sizes, shapes, overflow handling with an optional 'More' menu, and optional split buttons.
version: 0.1.0
#homepage: https://bruckcode.de
repository: https://github.com/EmilyMonestone/button_group
issue_tracker: https://github.com/EmilyMonestone/button_group/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#screenshots:

flutter:
  uses-material-design: true

